import type { Metadata } from 'next';
import './globals.css';
import Layout from '../components/layout/index';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};


export default function requestLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <Layout>
          <div>
            <main>{children}</main>
          </div>
        </Layout>
      </body>  
      </html>
    );
}
