import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className="font-pretendard">
				<div className="flex">
					<Navbar />
					<div>
						<Header />
						<main>{children}</main>
					</div>
				</div>
			</body>
		</html>
	);
}
